// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SmartBike.API.Migrations
{
    [DbContext(typeof(SmartBikeAPIContext))]
    partial class SmartBikeAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartBike.Entidades.Camara", b =>
                {
                    b.Property<int>("IdCam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idcam");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCam"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("IdCamara")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id_camara");

                    b.Property<int>("IdTipoTransporte")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_transporte");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpCamara")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_camara");

                    b.HasKey("IdCam");

                    b.HasIndex("IdTipoTransporte");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Camaras");
                });

            modelBuilder.Entity("SmartBike.Entidades.ConteoCamara", b =>
                {
                    b.Property<int>("IdConteCama")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_conte_cama");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConteCama"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdTipoTransporte")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_transporte");

                    b.Property<string>("IpCamara")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_camara");

                    b.Property<string>("NombreCamara")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nombre_camara");

                    b.HasKey("IdConteCama");

                    b.HasIndex("IdTipoTransporte");

                    b.ToTable("ConteoCamaras");
                });

            modelBuilder.Entity("SmartBike.Entidades.Historial", b =>
                {
                    b.Property<int>("IdHi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idhi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHi"));

                    b.Property<decimal>("Co2Acumulado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("co2_acumulado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdTipoTransporte")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_transporte");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdHi");

                    b.HasIndex("IdTipoTransporte");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Historiales");
                });

            modelBuilder.Entity("SmartBike.Entidades.RegistroDiario", b =>
                {
                    b.Property<int>("IdReg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idreg");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReg"));

                    b.Property<decimal>("Co2Generado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("co2_generado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCamara")
                        .HasColumnType("int")
                        .HasColumnName("id_camara");

                    b.Property<int>("IdTipoTransporte")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_transporte");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdReg");

                    b.HasIndex("IdCamara");

                    b.HasIndex("IdTipoTransporte");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RegistroDiarios");
                });

            modelBuilder.Entity("SmartBike.Entidades.Reporte", b =>
                {
                    b.Property<int>("IdRep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idrep");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRep"));

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_generacion");

                    b.Property<int>("IdTipoTransporte")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_transporte");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("periodo");

                    b.Property<decimal>("TotalCo2")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("total_co2");

                    b.HasKey("IdRep");

                    b.HasIndex("IdTipoTransporte");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("SmartBike.Entidades.TipoTransporte", b =>
                {
                    b.Property<int>("IdTipTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtiptra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipTra"));

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("detalles");

                    b.Property<bool>("EsCeroEmision")
                        .HasColumnType("bit")
                        .HasColumnName("es_cero_emision");

                    b.HasKey("IdTipTra");

                    b.ToTable("TipoTransportes");
                });

            modelBuilder.Entity("SmartBike.Entidades.TipoUsuario", b =>
                {
                    b.Property<int>("IdTip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idtip");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTip"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("detalle");

                    b.HasKey("IdTip");

                    b.ToTable("TipoUsuarios");
                });

            modelBuilder.Entity("SmartBike.Entidades.Usuario", b =>
                {
                    b.Property<string>("Cedula")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("cedula");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("correo_institucional");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecharegistro");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_usuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nombres");

                    b.HasKey("Cedula");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SmartBike.Entidades.Camara", b =>
                {
                    b.HasOne("SmartBike.Entidades.TipoTransporte", "TipoTransporte")
                        .WithMany()
                        .HasForeignKey("IdTipoTransporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBike.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoTransporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBike.Entidades.ConteoCamara", b =>
                {
                    b.HasOne("SmartBike.Entidades.TipoTransporte", "TipoTransporte")
                        .WithMany()
                        .HasForeignKey("IdTipoTransporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTransporte");
                });

            modelBuilder.Entity("SmartBike.Entidades.Historial", b =>
                {
                    b.HasOne("SmartBike.Entidades.TipoTransporte", "TipoTransporte")
                        .WithMany()
                        .HasForeignKey("IdTipoTransporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartBike.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTransporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBike.Entidades.RegistroDiario", b =>
                {
                    b.HasOne("SmartBike.Entidades.Camara", "Camara")
                        .WithMany()
                        .HasForeignKey("IdCamara")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartBike.Entidades.TipoTransporte", "TipoTransporte")
                        .WithMany()
                        .HasForeignKey("IdTipoTransporte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartBike.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camara");

                    b.Navigation("TipoTransporte");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartBike.Entidades.Reporte", b =>
                {
                    b.HasOne("SmartBike.Entidades.TipoTransporte", "TipoTransporte")
                        .WithMany()
                        .HasForeignKey("IdTipoTransporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTransporte");
                });

            modelBuilder.Entity("SmartBike.Entidades.Usuario", b =>
                {
                    b.HasOne("SmartBike.Entidades.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("IdTipoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
